openapi: 3.0.1
info:
  title: Circle of Trust API
  version: 1.4.0-SNAPSHOT
servers:
  - url: https://acme.symphony.com
tags:
  - name: Circle Of Trust
    description: For extension app authentication. See [Circle of Trust](https://docs.developers.symphony.com/building-extension-applications-on-symphony/app-authentication/circle-of-trust-authentication) documentation.
paths:
  '/bdk/v1/app/auth':
    post:
      tags:
        - Circle Of Trust
      summary: Application Authenticate
      operationId: appAuth
      requestBody:
        content: {}
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppToken'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/bdk/v1/app/tokens':
    post:
      tags:
        - Circle Of Trust
      summary: Validate Tokens
      operationId: validateTokens
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenPair'
      responses:
        204:
          description: Success
          content: {}
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  '/bdk/v1/app/jwt':
    post:
      tags:
        - Circle Of Trust
      summary: Validate JWT
      operationId: validateJwt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Jwt'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AppToken:
      type: object
      properties:
        appToken:
          type: string
    TokenPair:
      type: object
      properties:
        appToken:
          type: string
        symphonyToken:
          type: string
    Jwt:
      type: object
      properties:
        jwt:
          type: string
    UserInfo:
      type: object
      properties:
        userId:
          type: number
          format: int64
    Error:
      type: object
      properties:
        status:
          type: number
          format: int32
        errorCode:
          type: string
        message:
          type: array
          items:
            type: string
