name: Build

on:
  push:
    branches: [ 'main', '*-rc' ]
  pull_request:
    branches: [ 'main', '*-rc' ]

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build jacocoTestReport jacocoTestCoverageVerification
