# https://github.com/gradle/wrapper-validation-action#readme

name: "Validate Gradle Wrapper"
on: [ push, pull_request ]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
